global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'fastapi'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8000']  # Adjust this based on your setup
